name: 'API: tests & dev deploy'

on:
  push:
    paths:
      - 'api/**'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/api-test-deploy-dev.yml'

env:
  AZURE_ACR_NAME: prtrdev.azurecr.io # set separately to jobs.tests.container.image
  AZURE_WEBAPP_NAME: prtr-api-dev

jobs:
  tests:
    name: Test API
    runs-on: ubuntu-latest
    container:
      image: sykeprtrprodacr.azurecr.io/fin-prtr:tests
      credentials:
        username: ${{ secrets.PROD_AZURE_CREDENTIALS_CLIENT_ID }}
        password: ${{ secrets.PROD_AZURE_CREDENTIALS_CLIENT_SECRET }}
    steps:
    - uses: actions/checkout@v2
    - name: Test PRTR API
      run: |
          cd api/
          python -m pytest tests/ -vv

  build-deploy-dev:
    name: Build & deploy dev
    if: github.ref == 'refs/heads/main' # TODO set deploy to run only in dev branch ("dev" ?)
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_ACR_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . \
          -t ${{ env.AZURE_ACR_NAME }}/fin-prtr:latest \
          -t ${{ env.AZURE_ACR_NAME }}/fin-prtr:${{ github.sha }}
        docker push ${{ env.AZURE_ACR_NAME }}/fin-prtr:latest
        docker push ${{ env.AZURE_ACR_NAME }}/fin-prtr:${{ github.sha }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ env.AZURE_ACR_NAME }}/fin-prtr:${{ github.sha }}'
