name: 'API: tests & deploy dev'

on:
  push:
    paths:
      - 'api/**'
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  tests:
    name: Test API
    runs-on: ubuntu-latest
    container:
      image: prtrdev.azurecr.io/fin-prtr:latest
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: Test PRTR API
      run: |
          cd api/
          python -m pytest tests/ -vv

  build-deploy-dev:
    name: Build & deploy dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: prtrdev.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . \
          -t prtrdev.azurecr.io/fin-prtr:latest \
          -t prtrdev.azurecr.io/fin-prtr:${{ github.sha }}
        docker push prtrdev.azurecr.io/fin-prtr:latest
        docker push prtrdev.azurecr.io/fin-prtr:${{ github.sha }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'prtr-api-dev'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'prtrdev.azurecr.io/fin-prtr:${{ github.sha }}'
