name: build test container
on:
  push:
    paths:
      - 'Dockerfile'
      - 'app/requirements.txt'
      - 'app/dev-env.yml'

jobs:
  build-latest:
    name: Build latest
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: prtrdev.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t prtrdev.azurecr.io/fin-prtr:latest
        docker push prtrdev.azurecr.io/fin-prtr:latest
