name: 'UI: build & tests'
on:
  push:
    paths:
      - 'ui/**'
      - '.github/workflows/ui-build-test.yml'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          project: ui
